export const ADMIN_CASH_PAYMENT_METHODS_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    name: { required: true, type: "string", maxLength: 255, minLength: 1 },
    description: { required: false, type: "string" },
  },
  additionalProperties: false,
};
export const ADMIN_CASH_TRANSACTIONS_TYPES_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    name: { required: true, type: "string", maxLength: 100, minLength: 1 },
    is_business_activity: { required: false, type: "boolean" },
    description: { required: false, type: "string" },
  },
  additionalProperties: false,
};
export const ADMIN_CASH_TRANSACTIONS_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    status: {
      required: false,
      type: "string",
      enum: ["Draft", "Confirmed"],
      default: "Draft",
    },
    flow_type: { required: false, type: "string", enum: ["Cash_out", "Cash_in"] },
    notes: { required: false, type: "string" },
    address: { required: false, type: "string" },
    amount: { required: true, type: "string", format: "decimal" },
    affect_creditor: { required: false, type: "boolean" },
    type: { required: true, type: "integer" },
    payment_method: { required: false, type: "integer", nullable: true },
    source_type: {
      title: "Source type",
      type: "string",
      enum: ["order.invoice", "stock.stockoutnote", "stock.receiptorder"],
      readOnly: true,
      nullable: true,
    },
    target_type: {
      title: "Target type",
      type: "string",
      enum: ["partner.partner", "customer.customer"],
      readOnly: true,
      nullable: true,
    },
    source_id: {
      title: "Source id",
      type: "integer",
      readOnly: true,
      maximum: 9223372036854776000,
      minimum: 0,
      nullable: true,
    },
    target_id: {
      title: "Target id",
      type: "integer",
      readOnly: true,
      maximum: 9223372036854776000,
      minimum: 0,
      nullable: true,
    },
    target_name: { title: "Target name", type: "string", readOnly: true, maxLength: 255 },
  },
  additionalProperties: false,
};
export const ADMIN_CUSTOMERS_DRAFTS_ADDRESSES_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    line1: {
      title: "Line1",
      type: "string",
      maxLength: 255,
      minLength: 1,
      required: true,
    },
    line2: { title: "Line2", type: "string", maxLength: 255 },
    district: { title: "District", type: "string", maxLength: 255 },
    ward: { title: "Ward", type: "string", maxLength: 255 },
    province: { title: "Province", type: "string", maxLength: 255 },
    postcode: { title: "Postcode", type: "string", maxLength: 64 },
    phone_number: { title: "Phone number", type: "string", maxLength: 128 },
    notes: { title: "Notes", type: "string" },
    is_default_for_shipping: { title: "Is default for shipping", type: "boolean" },
    is_default_for_shipping_ecom: {
      title: "Is default for shipping ecom",
      type: "boolean",
    },
    is_default_for_billing: { title: "Is default for billing", type: "boolean" },
    country: {
      title: "Country",
      type: "string",
      enum: [
        "AF",
        "AX",
        "AL",
        "DZ",
        "AS",
        "AD",
        "AO",
        "AI",
        "AQ",
        "AG",
        "AR",
        "AM",
        "AW",
        "AU",
        "AT",
        "AZ",
        "BS",
        "BH",
        "BD",
        "BB",
        "BY",
        "BE",
        "BZ",
        "BJ",
        "BM",
        "BT",
        "BO",
        "BQ",
        "BA",
        "BW",
        "BV",
        "BR",
        "IO",
        "BN",
        "BG",
        "BF",
        "BI",
        "CV",
        "KH",
        "CM",
        "CA",
        "KY",
        "CF",
        "TD",
        "CL",
        "CN",
        "CX",
        "CC",
        "CO",
        "KM",
        "CG",
        "CD",
        "CK",
        "CR",
        "CI",
        "HR",
        "CU",
        "CW",
        "CY",
        "CZ",
        "DK",
        "DJ",
        "DM",
        "DO",
        "EC",
        "EG",
        "SV",
        "GQ",
        "ER",
        "EE",
        "SZ",
        "ET",
        "FK",
        "FO",
        "FJ",
        "FI",
        "FR",
        "GF",
        "PF",
        "TF",
        "GA",
        "GM",
        "GE",
        "DE",
        "GH",
        "GI",
        "GR",
        "GL",
        "GD",
        "GP",
        "GU",
        "GT",
        "GG",
        "GN",
        "GW",
        "GY",
        "HT",
        "HM",
        "VA",
        "HN",
        "HK",
        "HU",
        "IS",
        "IN",
        "ID",
        "IR",
        "IQ",
        "IE",
        "IM",
        "IL",
        "IT",
        "JM",
        "JP",
        "JE",
        "JO",
        "KZ",
        "KE",
        "KI",
        "KW",
        "KG",
        "LA",
        "LV",
        "LB",
        "LS",
        "LR",
        "LY",
        "LI",
        "LT",
        "LU",
        "MO",
        "MG",
        "MW",
        "MY",
        "MV",
        "ML",
        "MT",
        "MH",
        "MQ",
        "MR",
        "MU",
        "YT",
        "MX",
        "FM",
        "MD",
        "MC",
        "MN",
        "ME",
        "MS",
        "MA",
        "MZ",
        "MM",
        "NA",
        "NR",
        "NP",
        "NL",
        "NC",
        "NZ",
        "NI",
        "NE",
        "NG",
        "NU",
        "NF",
        "KP",
        "MK",
        "MP",
        "NO",
        "OM",
        "PK",
        "PW",
        "PS",
        "PA",
        "PG",
        "PY",
        "PE",
        "PH",
        "PN",
        "PL",
        "PT",
        "PR",
        "QA",
        "RE",
        "RO",
        "RU",
        "RW",
        "BL",
        "SH",
        "KN",
        "LC",
        "MF",
        "PM",
        "VC",
        "WS",
        "SM",
        "ST",
        "SA",
        "SN",
        "RS",
        "SC",
        "SL",
        "SG",
        "SX",
        "SK",
        "SI",
        "SB",
        "SO",
        "ZA",
        "GS",
        "KR",
        "SS",
        "ES",
        "LK",
        "SD",
        "SR",
        "SJ",
        "SE",
        "CH",
        "SY",
        "TW",
        "TJ",
        "TZ",
        "TH",
        "TL",
        "TG",
        "TK",
        "TO",
        "TT",
        "TN",
        "TR",
        "TM",
        "TC",
        "TV",
        "UG",
        "UA",
        "AE",
        "GB",
        "UM",
        "US",
        "UY",
        "UZ",
        "VU",
        "VE",
        "VN",
        "VG",
        "VI",
        "WF",
        "EH",
        "YE",
        "ZM",
        "ZW",
      ],
    },
    user: { title: "User", type: "integer", readOnly: true },
    coordinates: {
      latitude: { title: "Latitude", type: "number", required: true },
      longitude: { title: "Longitude", type: "number", required: true },
      type: "object",
      nullable: true,
    },
  },
  additionalProperties: false,
};
export const ADMIN_CUSTOMERS_DRAFTS_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    avatar: { required: false, type: "file", nullable: true },
    email: {
      required: false,
      type: "string",
      format: "email",
      maxLength: 254,
      nullable: true,
    },
    main_phone_number: {
      required: false,
      type: "string",
      maxLength: 128,
      nullable: true,
    },
    first_name: { required: false, type: "string", maxLength: 128 },
    last_name: { required: false, type: "string", maxLength: 128 },
    note: { required: false, type: "string" },
    birthday: { required: false, type: "string", format: "date-time", nullable: true },
    gender: { required: false, type: "string", enum: ["Male", "Female", "Other"] },
    facebook: { required: false, type: "string", format: "uri", maxLength: 200 },
    tax_identification_number: {
      required: false,
      type: "string",
      maxLength: 20,
      nullable: true,
    },
    company_name: { required: false, type: "string", maxLength: 255 },
    in_business: { required: false, type: "boolean" },
    type: { required: false, type: "integer", nullable: true },
  },
  additionalProperties: false,
};
export const ADMIN_CUSTOMERS_TYPES_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    name: { required: true, type: "string", maxLength: 255, minLength: 1 },
    description: { required: false, type: "string" },
    parent: { required: false, type: "integer", nullable: true },
  },
  additionalProperties: false,
};
export const ADMIN_CUSTOMERS_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    sales_in_charge: { required: false, type: "integer", nullable: true },
    max_debt: { required: false, type: "string", format: "decimal" },
  },
  additionalProperties: false,
};
export const ADMIN_DISCOUNTS_DISCOUNTED_VARIANTS_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    discount_type: { required: false, type: "string", enum: ["Percentage", "Absolute"] },
    discount_amount: { required: false, type: "string", format: "decimal" },
    usage_limit: {
      required: false,
      type: "integer",
      maximum: 2147483647,
      minimum: 0,
      nullable: true,
    },
    variant: { title: "Variant", type: "integer", readOnly: true },
    sale: { title: "Sale", type: "integer", readOnly: true },
  },
  additionalProperties: false,
};
export const ADMIN_DISCOUNTS_VOUCHERS_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    type: {
      required: false,
      type: "string",
      enum: ["Entire_order", "Specific_product_variant"],
    },
    name: { required: true, type: "string", maxLength: 255, minLength: 1 },
    code: { required: true, type: "string", maxLength: 255, minLength: 1 },
    description: { required: false, type: "string" },
    usage_limit: {
      required: false,
      type: "integer",
      maximum: 2147483647,
      minimum: 0,
      nullable: true,
    },
    date_start: { required: false, type: "string", format: "date-time" },
    date_end: { required: false, type: "string", format: "date-time", nullable: true },
    apply_once_per_order: { required: false, type: "boolean" },
    apply_once_per_customer: { required: false, type: "boolean" },
    standalone: { required: false, type: "boolean" },
    discount_type: { required: false, type: "string", enum: ["Percentage", "Absolute"] },
    discount_amount: { required: false, type: "string", format: "decimal" },
    min_spent_amount: { required: false, type: "string", format: "decimal" },
    min_checkout_items_quantity: {
      required: false,
      type: "integer",
      maximum: 2147483647,
      minimum: 0,
    },
    max_discount_amount: {
      required: false,
      type: "string",
      format: "decimal",
      nullable: true,
    },
  },
  additionalProperties: false,
};
export const ADMIN_DISCOUNTS_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    name: { required: true, type: "string", maxLength: 255, minLength: 1 },
    date_start: { required: false, type: "string", format: "date-time" },
    date_end: { required: false, type: "string", format: "date-time", nullable: true },
  },
  additionalProperties: false,
};
export const ADMIN_ISSUES_RELATED_ITEMS_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: { extra: { required: false, type: "string" } },
  additionalProperties: false,
};
export const ADMIN_ISSUES_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    title: { required: true, type: "string", maxLength: 255, minLength: 1 },
    description: { required: true, type: "string", minLength: 1 },
  },
  additionalProperties: false,
};
export const ADMIN_ORDERS_BILLING_ADDRESSES_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    line1: { required: true, type: "string", maxLength: 255, minLength: 1 },
    line2: { required: false, type: "string", maxLength: 255 },
    ward: { required: false, type: "string", maxLength: 255 },
    district: { required: false, type: "string", maxLength: 255 },
    province: { required: false, type: "string", maxLength: 255 },
    country: {
      required: false,
      type: "string",
      enum: [
        "AF",
        "AX",
        "AL",
        "DZ",
        "AS",
        "AD",
        "AO",
        "AI",
        "AQ",
        "AG",
        "AR",
        "AM",
        "AW",
        "AU",
        "AT",
        "AZ",
        "BS",
        "BH",
        "BD",
        "BB",
        "BY",
        "BE",
        "BZ",
        "BJ",
        "BM",
        "BT",
        "BO",
        "BQ",
        "BA",
        "BW",
        "BV",
        "BR",
        "IO",
        "BN",
        "BG",
        "BF",
        "BI",
        "CV",
        "KH",
        "CM",
        "CA",
        "KY",
        "CF",
        "TD",
        "CL",
        "CN",
        "CX",
        "CC",
        "CO",
        "KM",
        "CG",
        "CD",
        "CK",
        "CR",
        "CI",
        "HR",
        "CU",
        "CW",
        "CY",
        "CZ",
        "DK",
        "DJ",
        "DM",
        "DO",
        "EC",
        "EG",
        "SV",
        "GQ",
        "ER",
        "EE",
        "SZ",
        "ET",
        "FK",
        "FO",
        "FJ",
        "FI",
        "FR",
        "GF",
        "PF",
        "TF",
        "GA",
        "GM",
        "GE",
        "DE",
        "GH",
        "GI",
        "GR",
        "GL",
        "GD",
        "GP",
        "GU",
        "GT",
        "GG",
        "GN",
        "GW",
        "GY",
        "HT",
        "HM",
        "VA",
        "HN",
        "HK",
        "HU",
        "IS",
        "IN",
        "ID",
        "IR",
        "IQ",
        "IE",
        "IM",
        "IL",
        "IT",
        "JM",
        "JP",
        "JE",
        "JO",
        "KZ",
        "KE",
        "KI",
        "KW",
        "KG",
        "LA",
        "LV",
        "LB",
        "LS",
        "LR",
        "LY",
        "LI",
        "LT",
        "LU",
        "MO",
        "MG",
        "MW",
        "MY",
        "MV",
        "ML",
        "MT",
        "MH",
        "MQ",
        "MR",
        "MU",
        "YT",
        "MX",
        "FM",
        "MD",
        "MC",
        "MN",
        "ME",
        "MS",
        "MA",
        "MZ",
        "MM",
        "NA",
        "NR",
        "NP",
        "NL",
        "NC",
        "NZ",
        "NI",
        "NE",
        "NG",
        "NU",
        "NF",
        "KP",
        "MK",
        "MP",
        "NO",
        "OM",
        "PK",
        "PW",
        "PS",
        "PA",
        "PG",
        "PY",
        "PE",
        "PH",
        "PN",
        "PL",
        "PT",
        "PR",
        "QA",
        "RE",
        "RO",
        "RU",
        "RW",
        "BL",
        "SH",
        "KN",
        "LC",
        "MF",
        "PM",
        "VC",
        "WS",
        "SM",
        "ST",
        "SA",
        "SN",
        "RS",
        "SC",
        "SL",
        "SG",
        "SX",
        "SK",
        "SI",
        "SB",
        "SO",
        "ZA",
        "GS",
        "KR",
        "SS",
        "ES",
        "LK",
        "SD",
        "SR",
        "SJ",
        "SE",
        "CH",
        "SY",
        "TW",
        "TJ",
        "TZ",
        "TH",
        "TL",
        "TG",
        "TK",
        "TO",
        "TT",
        "TN",
        "TR",
        "TM",
        "TC",
        "TV",
        "UG",
        "UA",
        "AE",
        "GB",
        "UM",
        "US",
        "UY",
        "UZ",
        "VU",
        "VE",
        "VN",
        "VG",
        "VI",
        "WF",
        "EH",
        "YE",
        "ZM",
        "ZW",
      ],
    },
    postcode: { required: false, type: "string", maxLength: 64 },
    phone_number: { required: false, type: "string", maxLength: 128 },
    notes: { required: false, type: "string" },
    order: { title: "Order", type: "integer", readOnly: true },
  },
  additionalProperties: false,
};
export const ADMIN_ORDERS_INVOICES_QUANTITIES_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    unit_quantity: { required: true, type: "integer", maximum: 2147483647, minimum: 1 },
    line: { title: "Line", type: "integer", readOnly: true },
    invoice: { title: "Invoice", type: "integer", readOnly: true },
    record: { title: "Record", type: "integer", readOnly: true, nullable: true },
    warehouse: { title: "Warehouse", type: "integer", readOnly: true, nullable: true },
  },
  additionalProperties: false,
};
export const ADMIN_ORDERS_INVOICES_RETURN_INVOICES_QUANTITIES_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    quantity: { required: false, type: "integer", maximum: 2147483647, minimum: 1 },
    return_invoice: { title: "Return invoice", type: "integer", readOnly: true },
    invoice_quantity: { title: "Invoice quantity", type: "integer", readOnly: true },
  },
  additionalProperties: false,
};
export const ADMIN_ORDERS_INVOICES_RETURN_INVOICES_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    surcharge: { required: false, type: "string", format: "decimal" },
    notes: { required: false, type: "string" },
    is_confirmed: { required: false, type: "boolean" },
    invoice: { title: "Invoice", type: "integer", readOnly: true },
  },
  additionalProperties: false,
};
export const ADMIN_ORDERS_INVOICES_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    status: { required: false, type: "string", enum: ["Draft"], default: "Draft" },
    shipping_status: {
      required: false,
      type: "string",
      enum: ["Pending"],
      default: "Pending",
    },
    cod: { required: false, type: "boolean" },
    shipping_incl_tax: { required: false, type: "string", format: "decimal" },
    shipping_excl_tax: { required: false, type: "string", format: "decimal" },
    surcharge: { required: false, type: "string", format: "decimal" },
    shipper: { required: false, type: "integer", nullable: true },
    order: { title: "Order", type: "integer", readOnly: true },
  },
  additionalProperties: false,
};
export const ADMIN_ORDERS_LINES_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    unit_quantity: { required: true, type: "integer", maximum: 2147483647, minimum: 1 },
    unit: { title: "Unit", type: "string", readOnly: true, maxLength: 128 },
    discount_type: {
      title: "Discount type",
      type: "string",
      enum: ["Percentage", "Absolute"],
      readOnly: true,
    },
    discount_amount: {
      title: "Discount amount",
      type: "string",
      format: "decimal",
      readOnly: true,
    },
    order: { title: "Order", type: "integer", readOnly: true },
    variant: { title: "Variant", type: "integer", readOnly: true },
  },
  additionalProperties: false,
};
export const ADMIN_ORDERS_PURCHASE_CHANNELS_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    name: { required: true, type: "string", maxLength: 255, minLength: 1 },
    description: { required: false, type: "string" },
  },
  additionalProperties: false,
};
export const ADMIN_ORDERS_SHIPPERS_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    user: { required: false, type: "integer", nullable: true },
    name: { required: true, type: "string", maxLength: 128, minLength: 1 },
  },
  additionalProperties: false,
};
export const ADMIN_ORDERS_SHIPPING_ADDRESSES_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    line1: { required: true, type: "string", maxLength: 255, minLength: 1 },
    line2: { required: false, type: "string", maxLength: 255 },
    ward: { required: false, type: "string", maxLength: 255 },
    district: { required: false, type: "string", maxLength: 255 },
    province: { required: false, type: "string", maxLength: 255 },
    country: {
      required: false,
      type: "string",
      enum: [
        "AF",
        "AX",
        "AL",
        "DZ",
        "AS",
        "AD",
        "AO",
        "AI",
        "AQ",
        "AG",
        "AR",
        "AM",
        "AW",
        "AU",
        "AT",
        "AZ",
        "BS",
        "BH",
        "BD",
        "BB",
        "BY",
        "BE",
        "BZ",
        "BJ",
        "BM",
        "BT",
        "BO",
        "BQ",
        "BA",
        "BW",
        "BV",
        "BR",
        "IO",
        "BN",
        "BG",
        "BF",
        "BI",
        "CV",
        "KH",
        "CM",
        "CA",
        "KY",
        "CF",
        "TD",
        "CL",
        "CN",
        "CX",
        "CC",
        "CO",
        "KM",
        "CG",
        "CD",
        "CK",
        "CR",
        "CI",
        "HR",
        "CU",
        "CW",
        "CY",
        "CZ",
        "DK",
        "DJ",
        "DM",
        "DO",
        "EC",
        "EG",
        "SV",
        "GQ",
        "ER",
        "EE",
        "SZ",
        "ET",
        "FK",
        "FO",
        "FJ",
        "FI",
        "FR",
        "GF",
        "PF",
        "TF",
        "GA",
        "GM",
        "GE",
        "DE",
        "GH",
        "GI",
        "GR",
        "GL",
        "GD",
        "GP",
        "GU",
        "GT",
        "GG",
        "GN",
        "GW",
        "GY",
        "HT",
        "HM",
        "VA",
        "HN",
        "HK",
        "HU",
        "IS",
        "IN",
        "ID",
        "IR",
        "IQ",
        "IE",
        "IM",
        "IL",
        "IT",
        "JM",
        "JP",
        "JE",
        "JO",
        "KZ",
        "KE",
        "KI",
        "KW",
        "KG",
        "LA",
        "LV",
        "LB",
        "LS",
        "LR",
        "LY",
        "LI",
        "LT",
        "LU",
        "MO",
        "MG",
        "MW",
        "MY",
        "MV",
        "ML",
        "MT",
        "MH",
        "MQ",
        "MR",
        "MU",
        "YT",
        "MX",
        "FM",
        "MD",
        "MC",
        "MN",
        "ME",
        "MS",
        "MA",
        "MZ",
        "MM",
        "NA",
        "NR",
        "NP",
        "NL",
        "NC",
        "NZ",
        "NI",
        "NE",
        "NG",
        "NU",
        "NF",
        "KP",
        "MK",
        "MP",
        "NO",
        "OM",
        "PK",
        "PW",
        "PS",
        "PA",
        "PG",
        "PY",
        "PE",
        "PH",
        "PN",
        "PL",
        "PT",
        "PR",
        "QA",
        "RE",
        "RO",
        "RU",
        "RW",
        "BL",
        "SH",
        "KN",
        "LC",
        "MF",
        "PM",
        "VC",
        "WS",
        "SM",
        "ST",
        "SA",
        "SN",
        "RS",
        "SC",
        "SL",
        "SG",
        "SX",
        "SK",
        "SI",
        "SB",
        "SO",
        "ZA",
        "GS",
        "KR",
        "SS",
        "ES",
        "LK",
        "SD",
        "SR",
        "SJ",
        "SE",
        "CH",
        "SY",
        "TW",
        "TJ",
        "TZ",
        "TH",
        "TL",
        "TG",
        "TK",
        "TO",
        "TT",
        "TN",
        "TR",
        "TM",
        "TC",
        "TV",
        "UG",
        "UA",
        "AE",
        "GB",
        "UM",
        "US",
        "UY",
        "UZ",
        "VU",
        "VE",
        "VN",
        "VG",
        "VI",
        "WF",
        "EH",
        "YE",
        "ZM",
        "ZW",
      ],
    },
    postcode: { required: false, type: "string", maxLength: 64 },
    phone_number: { required: false, type: "string", maxLength: 128 },
    notes: { required: false, type: "string" },
    order: { title: "Order", type: "integer", readOnly: true },
  },
  additionalProperties: false,
};
export const ADMIN_ORDERS_SHIPPING_METHODS_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    name: { required: true, type: "string", maxLength: 128, minLength: 1 },
    type: { required: true, type: "string", enum: ["Price", "Weight"] },
    price: { required: false, type: "string", format: "decimal" },
    price_incl_tax: { required: false, type: "string", format: "decimal" },
    minimum_order_price: { required: false, type: "string", format: "decimal" },
    maximum_order_price: {
      required: false,
      type: "string",
      format: "decimal",
      nullable: true,
    },
    minimum_order_weight: { required: false, type: "number", minimum: 0 },
    maximum_order_weight: { required: false, type: "number", nullable: true },
  },
  additionalProperties: false,
};
export const ADMIN_ORDERS_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    receiver: { required: false, type: "integer", nullable: true },
    receiver_name: { required: false, type: "string", maxLength: 256 },
    receiver_email: { required: false, type: "string", format: "email", maxLength: 254 },
    receiver_phone_number: {
      required: false,
      type: "string",
      maxLength: 128,
      nullable: true,
    },
    status: { required: false, type: "string", enum: ["Draft"], default: "Draft" },
    customer_notes: { required: false, type: "string" },
    channel: { required: false, type: "integer", nullable: true },
    shipping_method: { required: false, type: "integer", nullable: true },
  },
  additionalProperties: false,
};
export const ADMIN_PARTNERS_ADDRESSES_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    phone_number: { required: false, type: "string", maxLength: 128 },
    line1: { required: true, type: "string", maxLength: 255, minLength: 1 },
    line2: { required: false, type: "string", maxLength: 255 },
    district: { required: false, type: "string", maxLength: 255 },
    ward: { required: false, type: "string", maxLength: 255 },
    province: { required: false, type: "string", maxLength: 255 },
    postcode: { required: false, type: "string", maxLength: 64 },
    country: {
      required: false,
      type: "string",
      enum: [
        "AF",
        "AX",
        "AL",
        "DZ",
        "AS",
        "AD",
        "AO",
        "AI",
        "AQ",
        "AG",
        "AR",
        "AM",
        "AW",
        "AU",
        "AT",
        "AZ",
        "BS",
        "BH",
        "BD",
        "BB",
        "BY",
        "BE",
        "BZ",
        "BJ",
        "BM",
        "BT",
        "BO",
        "BQ",
        "BA",
        "BW",
        "BV",
        "BR",
        "IO",
        "BN",
        "BG",
        "BF",
        "BI",
        "CV",
        "KH",
        "CM",
        "CA",
        "KY",
        "CF",
        "TD",
        "CL",
        "CN",
        "CX",
        "CC",
        "CO",
        "KM",
        "CG",
        "CD",
        "CK",
        "CR",
        "CI",
        "HR",
        "CU",
        "CW",
        "CY",
        "CZ",
        "DK",
        "DJ",
        "DM",
        "DO",
        "EC",
        "EG",
        "SV",
        "GQ",
        "ER",
        "EE",
        "SZ",
        "ET",
        "FK",
        "FO",
        "FJ",
        "FI",
        "FR",
        "GF",
        "PF",
        "TF",
        "GA",
        "GM",
        "GE",
        "DE",
        "GH",
        "GI",
        "GR",
        "GL",
        "GD",
        "GP",
        "GU",
        "GT",
        "GG",
        "GN",
        "GW",
        "GY",
        "HT",
        "HM",
        "VA",
        "HN",
        "HK",
        "HU",
        "IS",
        "IN",
        "ID",
        "IR",
        "IQ",
        "IE",
        "IM",
        "IL",
        "IT",
        "JM",
        "JP",
        "JE",
        "JO",
        "KZ",
        "KE",
        "KI",
        "KW",
        "KG",
        "LA",
        "LV",
        "LB",
        "LS",
        "LR",
        "LY",
        "LI",
        "LT",
        "LU",
        "MO",
        "MG",
        "MW",
        "MY",
        "MV",
        "ML",
        "MT",
        "MH",
        "MQ",
        "MR",
        "MU",
        "YT",
        "MX",
        "FM",
        "MD",
        "MC",
        "MN",
        "ME",
        "MS",
        "MA",
        "MZ",
        "MM",
        "NA",
        "NR",
        "NP",
        "NL",
        "NC",
        "NZ",
        "NI",
        "NE",
        "NG",
        "NU",
        "NF",
        "KP",
        "MK",
        "MP",
        "NO",
        "OM",
        "PK",
        "PW",
        "PS",
        "PA",
        "PG",
        "PY",
        "PE",
        "PH",
        "PN",
        "PL",
        "PT",
        "PR",
        "QA",
        "RE",
        "RO",
        "RU",
        "RW",
        "BL",
        "SH",
        "KN",
        "LC",
        "MF",
        "PM",
        "VC",
        "WS",
        "SM",
        "ST",
        "SA",
        "SN",
        "RS",
        "SC",
        "SL",
        "SG",
        "SX",
        "SK",
        "SI",
        "SB",
        "SO",
        "ZA",
        "GS",
        "KR",
        "SS",
        "ES",
        "LK",
        "SD",
        "SR",
        "SJ",
        "SE",
        "CH",
        "SY",
        "TW",
        "TJ",
        "TZ",
        "TH",
        "TL",
        "TG",
        "TK",
        "TO",
        "TT",
        "TN",
        "TR",
        "TM",
        "TC",
        "TV",
        "UG",
        "UA",
        "AE",
        "GB",
        "UM",
        "US",
        "UY",
        "UZ",
        "VU",
        "VE",
        "VN",
        "VG",
        "VI",
        "WF",
        "EH",
        "YE",
        "ZM",
        "ZW",
      ],
    },
    partner: { title: "Partner", type: "integer", readOnly: true },
  },
  additionalProperties: false,
};
export const ADMIN_PARTNERS_ITEMS_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    partner_sku: { required: true, type: "string", maxLength: 255, minLength: 1 },
    price: { required: false, type: "string", format: "decimal" },
    price_incl_tax: { required: false, type: "string", format: "decimal" },
    partner: { title: "Partner", type: "integer", readOnly: true },
    variant: { title: "Variant", type: "integer", readOnly: true },
  },
  additionalProperties: false,
};
export const ADMIN_PARTNERS_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    max_debt: { required: false, type: "string", format: "decimal" },
    name: { required: true, type: "string", maxLength: 255, minLength: 1 },
    tax_identification_number: {
      required: false,
      type: "string",
      maxLength: 20,
      nullable: true,
    },
    notes: { required: false, type: "string" },
    email: { required: false, type: "string", format: "email", maxLength: 254 },
    contact_info: { required: false, type: "string" },
  },
  additionalProperties: false,
};
export const ADMIN_PRICE_TABLES_VARIANTS_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    change_type: {
      required: true,
      type: "string",
      enum: [
        "discount_percentage",
        "discount_absolute",
        "fixed_price",
        "increase_percentage",
        "increase_absolute",
      ],
    },
    change_amount: { required: false, type: "string", format: "decimal" },
    table: { required: true, type: "integer" },
    variant: { required: true, type: "integer" },
    unit: { required: false, type: "integer", nullable: true },
  },
  additionalProperties: false,
};
export const ADMIN_PRICE_TABLES_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    name: { required: true, type: "string", maxLength: 255, minLength: 1 },
    active: { required: false, type: "boolean" },
    date_start: { required: false, type: "string", format: "date-time" },
    date_end: { required: false, type: "string", format: "date-time", nullable: true },
    id: { title: "ID", type: "integer", readOnly: true },
    date_created: {
      title: "Date created",
      type: "string",
      format: "date-time",
      readOnly: true,
    },
    date_updated: {
      title: "Date updated",
      type: "string",
      format: "date-time",
      readOnly: true,
    },
  },
  additionalProperties: false,
};
export const ADMIN_PRODUCTS_ATTRIBUTES_OPTIONS_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    name: { required: true, type: "string", maxLength: 250, minLength: 1 },
    value: { required: true, type: "string", maxLength: 100, minLength: 1 },
    attribute: { title: "Attribute", type: "integer", readOnly: true },
  },
  additionalProperties: false,
};
export const ADMIN_PRODUCTS_ATTRIBUTES_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    input_type: { required: true, type: "string", enum: ["Option", "Multi_option"] },
    name: { required: true, type: "string", maxLength: 255, minLength: 1 },
    is_variant_only: { required: false, type: "boolean" },
  },
  additionalProperties: false,
};
export const ADMIN_PRODUCTS_CATEGORIES_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    parent: { required: false, type: "integer", nullable: true },
    name: { required: true, type: "string", maxLength: 250, minLength: 1 },
    description: { required: false, type: "string" },
    image: { required: false, type: "file", nullable: true },
    image_alt: { required: false, type: "string", maxLength: 128 },
  },
  additionalProperties: false,
};
export const ADMIN_PRODUCTS_IMAGES_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    sort_order: {
      required: false,
      type: "integer",
      maximum: 2147483647,
      minimum: 0,
      nullable: true,
    },
    alt: { required: false, type: "string", maxLength: 128 },
    image: { title: "Image", type: "string", readOnly: true, format: "uri" },
    product: { title: "Product", type: "integer", readOnly: true },
  },
  additionalProperties: false,
};
export const ADMIN_PRODUCTS_RECOMMENDATIONS_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    ranking: {
      description:
        "Determines order of the products. A product with a higher value will appear before one with a lower ranking.",
      required: false,
      type: "integer",
      maximum: 32767,
      minimum: 0,
    },
    primary: { title: "Primary", type: "integer", readOnly: true },
    recommendation: { title: "Recommendation", type: "integer", readOnly: true },
  },
  additionalProperties: false,
};
export const ADMIN_PRODUCTS_TYPES_PRODUCT_ATTRIBUTES_VALUES_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    values: {
      required: true,
      type: "array",
      items: { type: "integer" },
      uniqueItems: true,
    },
  },
  additionalProperties: false,
};
export const ADMIN_PRODUCTS_TYPES_VARIANT_ATTRIBUTES_VALUES_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    values: {
      required: true,
      type: "array",
      items: { type: "integer" },
      uniqueItems: true,
    },
  },
  additionalProperties: false,
};
export const ADMIN_PRODUCTS_TYPES_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    name: { required: true, type: "string", maxLength: 250, minLength: 1 },
    tax_rate: { required: false, type: "string", format: "decimal" },
    has_variants: { required: false, type: "boolean" },
  },
  additionalProperties: false,
};
export const ADMIN_PRODUCTS_VARIANTS_UNITS_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    editable_sku: { required: false, type: "string", maxLength: 255, minLength: 1 },
    unit: { required: true, type: "string", maxLength: 100, minLength: 1 },
    multiply: { required: false, type: "integer", maximum: 2147483647, minimum: 1 },
    weight: { required: false, type: "number", minimum: 0 },
    bar_code: { required: false, type: "string", maxLength: 100 },
    price: { required: false, type: "string", format: "decimal" },
    price_incl_tax: { required: false, type: "string", format: "decimal" },
    is_published: { required: false, type: "boolean" },
    variant: { title: "Variant", type: "integer", readOnly: true },
  },
  additionalProperties: false,
};
export const ADMIN_PRODUCTS_VARIANTS_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    is_default: { required: false, type: "boolean" },
    editable_sku: { required: false, type: "string", maxLength: 255, minLength: 1 },
    unit: { required: true, type: "string", maxLength: 100, minLength: 1 },
    weight: { required: false, type: "number", minimum: 0 },
    bar_code: { required: false, type: "string", maxLength: 100 },
    name: { required: false, type: "string", maxLength: 255 },
    track_inventory: { required: false, type: "boolean" },
    price: { required: false, type: "string", format: "decimal" },
    price_incl_tax: { required: false, type: "string", format: "decimal" },
    list_id_values: { required: false, type: "string", default: "", minLength: 1 },
    product: { title: "Product", type: "integer", readOnly: true },
  },
  additionalProperties: false,
};
export const ADMIN_PRODUCTS_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    publication_date: { required: false, type: "string", format: "date-time" },
    is_published: { required: false, type: "boolean" },
    meta_title: { required: false, type: "string", maxLength: 255 },
    meta_description: { required: false, type: "string" },
    seo_title: { required: false, type: "string", maxLength: 70 },
    seo_description: { required: false, type: "string", maxLength: 300 },
    name: { required: true, type: "string", maxLength: 250, minLength: 1 },
    description: { required: false, type: "string" },
    available_for_purchase: {
      required: false,
      type: "string",
      format: "date-time",
      nullable: true,
    },
    product_class: { title: "Product class", type: "integer", readOnly: true },
  },
  additionalProperties: false,
};
export const ADMIN_SETTINGS_PATCH_SCHEMA = {
  type: "object",
  properties: {
    logo: { required: false, type: "file", nullable: true },
    line1: { required: true, type: "string", maxLength: 255, minLength: 1 },
    line2: { required: false, type: "string", maxLength: 255 },
    ward: { required: false, type: "string", maxLength: 255 },
    district: { required: false, type: "string", maxLength: 255 },
    province: { required: false, type: "string", maxLength: 255 },
    country: {
      required: false,
      type: "string",
      enum: [
        "AF",
        "AX",
        "AL",
        "DZ",
        "AS",
        "AD",
        "AO",
        "AI",
        "AQ",
        "AG",
        "AR",
        "AM",
        "AW",
        "AU",
        "AT",
        "AZ",
        "BS",
        "BH",
        "BD",
        "BB",
        "BY",
        "BE",
        "BZ",
        "BJ",
        "BM",
        "BT",
        "BO",
        "BQ",
        "BA",
        "BW",
        "BV",
        "BR",
        "IO",
        "BN",
        "BG",
        "BF",
        "BI",
        "CV",
        "KH",
        "CM",
        "CA",
        "KY",
        "CF",
        "TD",
        "CL",
        "CN",
        "CX",
        "CC",
        "CO",
        "KM",
        "CG",
        "CD",
        "CK",
        "CR",
        "CI",
        "HR",
        "CU",
        "CW",
        "CY",
        "CZ",
        "DK",
        "DJ",
        "DM",
        "DO",
        "EC",
        "EG",
        "SV",
        "GQ",
        "ER",
        "EE",
        "SZ",
        "ET",
        "FK",
        "FO",
        "FJ",
        "FI",
        "FR",
        "GF",
        "PF",
        "TF",
        "GA",
        "GM",
        "GE",
        "DE",
        "GH",
        "GI",
        "GR",
        "GL",
        "GD",
        "GP",
        "GU",
        "GT",
        "GG",
        "GN",
        "GW",
        "GY",
        "HT",
        "HM",
        "VA",
        "HN",
        "HK",
        "HU",
        "IS",
        "IN",
        "ID",
        "IR",
        "IQ",
        "IE",
        "IM",
        "IL",
        "IT",
        "JM",
        "JP",
        "JE",
        "JO",
        "KZ",
        "KE",
        "KI",
        "KW",
        "KG",
        "LA",
        "LV",
        "LB",
        "LS",
        "LR",
        "LY",
        "LI",
        "LT",
        "LU",
        "MO",
        "MG",
        "MW",
        "MY",
        "MV",
        "ML",
        "MT",
        "MH",
        "MQ",
        "MR",
        "MU",
        "YT",
        "MX",
        "FM",
        "MD",
        "MC",
        "MN",
        "ME",
        "MS",
        "MA",
        "MZ",
        "MM",
        "NA",
        "NR",
        "NP",
        "NL",
        "NC",
        "NZ",
        "NI",
        "NE",
        "NG",
        "NU",
        "NF",
        "KP",
        "MK",
        "MP",
        "NO",
        "OM",
        "PK",
        "PW",
        "PS",
        "PA",
        "PG",
        "PY",
        "PE",
        "PH",
        "PN",
        "PL",
        "PT",
        "PR",
        "QA",
        "RE",
        "RO",
        "RU",
        "RW",
        "BL",
        "SH",
        "KN",
        "LC",
        "MF",
        "PM",
        "VC",
        "WS",
        "SM",
        "ST",
        "SA",
        "SN",
        "RS",
        "SC",
        "SL",
        "SG",
        "SX",
        "SK",
        "SI",
        "SB",
        "SO",
        "ZA",
        "GS",
        "KR",
        "SS",
        "ES",
        "LK",
        "SD",
        "SR",
        "SJ",
        "SE",
        "CH",
        "SY",
        "TW",
        "TJ",
        "TZ",
        "TH",
        "TL",
        "TG",
        "TK",
        "TO",
        "TT",
        "TN",
        "TR",
        "TM",
        "TC",
        "TV",
        "UG",
        "UA",
        "AE",
        "GB",
        "UM",
        "US",
        "UY",
        "UZ",
        "VU",
        "VE",
        "VN",
        "VG",
        "VI",
        "WF",
        "EH",
        "YE",
        "ZM",
        "ZW",
      ],
    },
    postcode: { required: false, type: "string", maxLength: 64 },
    company_name: { required: false, type: "string", maxLength: 254 },
    store_name: { required: false, type: "string", maxLength: 100 },
    store_description: { required: false, type: "string" },
    store_website: { required: false, type: "string", format: "uri", maxLength: 200 },
    hotline_1: { required: false, type: "string", maxLength: 128 },
    hotline_2: { required: false, type: "string", maxLength: 128 },
    tax_identification_number: { required: false, type: "string", maxLength: 20 },
    currency: {
      required: false,
      type: "string",
      enum: [
        "ADP",
        "AFA",
        "ALK",
        "AON",
        "AOR",
        "ARA",
        "ARP",
        "ATS",
        "AZM",
        "BAD",
        "BEF",
        "BGL",
        "BRC",
        "BRE",
        "BRN",
        "BRR",
        "BYR",
        "CLE",
        "CSD",
        "CSK",
        "CYP",
        "DDM",
        "DEM",
        "ECS",
        "ECV",
        "EEK",
        "ESA",
        "ESB",
        "ESP",
        "FIM",
        "FRF",
        "GHC",
        "GRD",
        "GWP",
        "HRD",
        "IEP",
        "ITL",
        "LTL",
        "LUF",
        "LVL",
        "MGF",
        "MLF",
        "MRO",
        "MTL",
        "MZM",
        "NLG",
        "PEI",
        "PLZ",
        "PTE",
        "ROL",
        "RUR",
        "SDD",
        "SIT",
        "SKK",
        "SRG",
        "STD",
        "TJR",
        "TMM",
        "TPE",
        "TRL",
        "UAK",
        "USS",
        "VEB",
        "VEF",
        "VNN",
        "XEU",
        "YDD",
        "YUM",
        "YUN",
        "ZAL",
        "ZMK",
        "ZRN",
        "ZRZ",
        "ZWD",
        "ZWL",
        "ZWR",
        "AOK",
        "ARL",
        "ARM",
        "BAN",
        "BEC",
        "BEL",
        "BGM",
        "BGO",
        "BOL",
        "BOP",
        "BRB",
        "BRZ",
        "BUK",
        "BYB",
        "CNH",
        "CNX",
        "GEK",
        "GNS",
        "GQE",
        "GWE",
        "ILP",
        "ILR",
        "ISJ",
        "KRH",
        "KRO",
        "LTT",
        "LUC",
        "LUL",
        "LVR",
        "MAF",
        "MCF",
        "MDC",
        "MKN",
        "MRU",
        "MTP",
        "MVP",
        "MXP",
        "MZE",
        "NIC",
        "PES",
        "RHD",
        "SDP",
        "STN",
        "SUR",
        "UGS",
        "UYP",
        "UYW",
        "VES",
        "XRE",
        "YUD",
        "YUR",
        "AED",
        "AFN",
        "ALL",
        "AMD",
        "ANG",
        "AOA",
        "ARS",
        "AUD",
        "AWG",
        "AZN",
        "BAM",
        "BBD",
        "BDT",
        "BGN",
        "BHD",
        "BIF",
        "BMD",
        "BND",
        "BOB",
        "BOV",
        "BRL",
        "BSD",
        "BTN",
        "BWP",
        "BYN",
        "BZD",
        "CAD",
        "CDF",
        "CHE",
        "CHF",
        "CHW",
        "CLF",
        "CLP",
        "CNY",
        "COP",
        "COU",
        "CRC",
        "CUC",
        "CUP",
        "CVE",
        "CZK",
        "DJF",
        "DKK",
        "DOP",
        "DZD",
        "EGP",
        "ERN",
        "ETB",
        "EUR",
        "FJD",
        "FKP",
        "GBP",
        "GEL",
        "GHS",
        "GIP",
        "GMD",
        "GNF",
        "GTQ",
        "GYD",
        "HKD",
        "HNL",
        "HRK",
        "HTG",
        "HUF",
        "IDR",
        "ILS",
        "IMP",
        "INR",
        "IQD",
        "IRR",
        "ISK",
        "JMD",
        "JOD",
        "JPY",
        "KES",
        "KGS",
        "KHR",
        "KMF",
        "KPW",
        "KRW",
        "KWD",
        "KYD",
        "KZT",
        "LAK",
        "LBP",
        "LKR",
        "LRD",
        "LSL",
        "LYD",
        "MAD",
        "MDL",
        "MGA",
        "MKD",
        "MMK",
        "MNT",
        "MOP",
        "MUR",
        "MVR",
        "MWK",
        "MXN",
        "MXV",
        "MYR",
        "MZN",
        "NAD",
        "NGN",
        "NIO",
        "NOK",
        "NPR",
        "NZD",
        "OMR",
        "PAB",
        "PEN",
        "PGK",
        "PHP",
        "PKR",
        "PLN",
        "PYG",
        "QAR",
        "RON",
        "RSD",
        "RUB",
        "RWF",
        "SAR",
        "SBD",
        "SCR",
        "SDG",
        "SEK",
        "SGD",
        "SHP",
        "SLE",
        "SLL",
        "SOS",
        "SRD",
        "SSP",
        "SVC",
        "SYP",
        "SZL",
        "THB",
        "TJS",
        "TMT",
        "TND",
        "TOP",
        "TRY",
        "TTD",
        "TVD",
        "TWD",
        "TZS",
        "UAH",
        "UGX",
        "USD",
        "USN",
        "UYI",
        "UYU",
        "UZS",
        "VED",
        "VND",
        "VUV",
        "WST",
        "XAF",
        "XAG",
        "XAU",
        "XBA",
        "XBB",
        "XBC",
        "XBD",
        "XCD",
        "XDR",
        "XFO",
        "XFU",
        "XOF",
        "XPD",
        "XPF",
        "XPT",
        "XSU",
        "XTS",
        "XUA",
        "XXX",
        "YER",
        "ZAR",
        "ZMW",
        "ZWN",
      ],
    },
    weight_unit: { required: false, type: "string", maxLength: 12, minLength: 1 },
    invoice_qr_code: { required: false, type: "file", nullable: true },
    invoice_notes: { required: false, type: "string" },
    bank_account_info: { required: false, type: "string" },
    invoice_qr_code_text: { required: false, type: "string" },
  },
  additionalProperties: false,
};
export const ADMIN_TAG_GROUPS_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    source_type: {
      required: true,
      type: "string",
      enum: [
        "order.order",
        "order.invoice",
        "customer.customer",
        "partner.partner",
        "issue.issue",
        "stock.purchaserequest",
      ],
    },
    tags: { required: true, type: "array", items: { type: "string", minLength: 1 } },
    name: { required: true, type: "string", maxLength: 255, minLength: 1 },
    id: { title: "ID", type: "integer", readOnly: true },
    date_created: {
      title: "Date created",
      type: "string",
      format: "date-time",
      readOnly: true,
    },
    date_updated: {
      title: "Date updated",
      type: "string",
      format: "date-time",
      readOnly: true,
    },
  },
  additionalProperties: false,
};
export const ADMIN_USERS_ADDRESSES_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    line1: {
      title: "Line1",
      type: "string",
      maxLength: 255,
      minLength: 1,
      required: true,
    },
    line2: { title: "Line2", type: "string", maxLength: 255 },
    district: { title: "District", type: "string", maxLength: 255 },
    ward: { title: "Ward", type: "string", maxLength: 255 },
    province: { title: "Province", type: "string", maxLength: 255 },
    postcode: { title: "Postcode", type: "string", maxLength: 64 },
    phone_number: { title: "Phone number", type: "string", maxLength: 128 },
    notes: { title: "Notes", type: "string" },
    is_default_for_shipping: { title: "Is default for shipping", type: "boolean" },
    is_default_for_billing: { title: "Is default for billing", type: "boolean" },
    country: {
      title: "Country",
      type: "string",
      enum: [
        "AF",
        "AX",
        "AL",
        "DZ",
        "AS",
        "AD",
        "AO",
        "AI",
        "AQ",
        "AG",
        "AR",
        "AM",
        "AW",
        "AU",
        "AT",
        "AZ",
        "BS",
        "BH",
        "BD",
        "BB",
        "BY",
        "BE",
        "BZ",
        "BJ",
        "BM",
        "BT",
        "BO",
        "BQ",
        "BA",
        "BW",
        "BV",
        "BR",
        "IO",
        "BN",
        "BG",
        "BF",
        "BI",
        "CV",
        "KH",
        "CM",
        "CA",
        "KY",
        "CF",
        "TD",
        "CL",
        "CN",
        "CX",
        "CC",
        "CO",
        "KM",
        "CG",
        "CD",
        "CK",
        "CR",
        "CI",
        "HR",
        "CU",
        "CW",
        "CY",
        "CZ",
        "DK",
        "DJ",
        "DM",
        "DO",
        "EC",
        "EG",
        "SV",
        "GQ",
        "ER",
        "EE",
        "SZ",
        "ET",
        "FK",
        "FO",
        "FJ",
        "FI",
        "FR",
        "GF",
        "PF",
        "TF",
        "GA",
        "GM",
        "GE",
        "DE",
        "GH",
        "GI",
        "GR",
        "GL",
        "GD",
        "GP",
        "GU",
        "GT",
        "GG",
        "GN",
        "GW",
        "GY",
        "HT",
        "HM",
        "VA",
        "HN",
        "HK",
        "HU",
        "IS",
        "IN",
        "ID",
        "IR",
        "IQ",
        "IE",
        "IM",
        "IL",
        "IT",
        "JM",
        "JP",
        "JE",
        "JO",
        "KZ",
        "KE",
        "KI",
        "KW",
        "KG",
        "LA",
        "LV",
        "LB",
        "LS",
        "LR",
        "LY",
        "LI",
        "LT",
        "LU",
        "MO",
        "MG",
        "MW",
        "MY",
        "MV",
        "ML",
        "MT",
        "MH",
        "MQ",
        "MR",
        "MU",
        "YT",
        "MX",
        "FM",
        "MD",
        "MC",
        "MN",
        "ME",
        "MS",
        "MA",
        "MZ",
        "MM",
        "NA",
        "NR",
        "NP",
        "NL",
        "NC",
        "NZ",
        "NI",
        "NE",
        "NG",
        "NU",
        "NF",
        "KP",
        "MK",
        "MP",
        "NO",
        "OM",
        "PK",
        "PW",
        "PS",
        "PA",
        "PG",
        "PY",
        "PE",
        "PH",
        "PN",
        "PL",
        "PT",
        "PR",
        "QA",
        "RE",
        "RO",
        "RU",
        "RW",
        "BL",
        "SH",
        "KN",
        "LC",
        "MF",
        "PM",
        "VC",
        "WS",
        "SM",
        "ST",
        "SA",
        "SN",
        "RS",
        "SC",
        "SL",
        "SG",
        "SX",
        "SK",
        "SI",
        "SB",
        "SO",
        "ZA",
        "GS",
        "KR",
        "SS",
        "ES",
        "LK",
        "SD",
        "SR",
        "SJ",
        "SE",
        "CH",
        "SY",
        "TW",
        "TJ",
        "TZ",
        "TH",
        "TL",
        "TG",
        "TK",
        "TO",
        "TT",
        "TN",
        "TR",
        "TM",
        "TC",
        "TV",
        "UG",
        "UA",
        "AE",
        "GB",
        "UM",
        "US",
        "UY",
        "UZ",
        "VU",
        "VE",
        "VN",
        "VG",
        "VI",
        "WF",
        "EH",
        "YE",
        "ZM",
        "ZW",
      ],
    },
    user: { title: "User", type: "integer", readOnly: true },
    coordinates: {
      latitude: { title: "Latitude", type: "number", required: true },
      longitude: { title: "Longitude", type: "number", required: true },
      type: "object",
      nullable: true,
    },
  },
  additionalProperties: false,
};
export const ADMIN_USERS_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    avatar: { required: false, type: "file", nullable: true },
    username: {
      required: false,
      type: "string",
      pattern: "^[\\w.+-]+$",
      maxLength: 255,
      nullable: true,
    },
    email: {
      required: false,
      type: "string",
      format: "email",
      maxLength: 254,
      nullable: true,
    },
    main_phone_number: {
      required: false,
      type: "string",
      maxLength: 128,
      nullable: true,
    },
    first_name: { required: false, type: "string", maxLength: 128 },
    last_name: { required: false, type: "string", maxLength: 128 },
    note: { required: false, type: "string" },
    birthday: { required: false, type: "string", format: "date-time", nullable: true },
    gender: { required: false, type: "string", enum: ["Male", "Female", "Other"] },
    facebook: { required: false, type: "string", format: "uri", maxLength: 200 },
    is_staff: { required: false, type: "boolean" },
    is_active: { required: false, type: "boolean" },
  },
  additionalProperties: false,
};
export const ADMIN_WAREHOUSES_ADDRESSES_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    line1: { required: true, type: "string", maxLength: 255, minLength: 1 },
    line2: { required: false, type: "string", maxLength: 255 },
    district: { required: false, type: "string", maxLength: 255 },
    ward: { required: false, type: "string", maxLength: 255 },
    province: { required: false, type: "string", maxLength: 255 },
    postcode: { required: false, type: "string", maxLength: 64 },
    country: {
      required: false,
      type: "string",
      enum: [
        "AF",
        "AX",
        "AL",
        "DZ",
        "AS",
        "AD",
        "AO",
        "AI",
        "AQ",
        "AG",
        "AR",
        "AM",
        "AW",
        "AU",
        "AT",
        "AZ",
        "BS",
        "BH",
        "BD",
        "BB",
        "BY",
        "BE",
        "BZ",
        "BJ",
        "BM",
        "BT",
        "BO",
        "BQ",
        "BA",
        "BW",
        "BV",
        "BR",
        "IO",
        "BN",
        "BG",
        "BF",
        "BI",
        "CV",
        "KH",
        "CM",
        "CA",
        "KY",
        "CF",
        "TD",
        "CL",
        "CN",
        "CX",
        "CC",
        "CO",
        "KM",
        "CG",
        "CD",
        "CK",
        "CR",
        "CI",
        "HR",
        "CU",
        "CW",
        "CY",
        "CZ",
        "DK",
        "DJ",
        "DM",
        "DO",
        "EC",
        "EG",
        "SV",
        "GQ",
        "ER",
        "EE",
        "SZ",
        "ET",
        "FK",
        "FO",
        "FJ",
        "FI",
        "FR",
        "GF",
        "PF",
        "TF",
        "GA",
        "GM",
        "GE",
        "DE",
        "GH",
        "GI",
        "GR",
        "GL",
        "GD",
        "GP",
        "GU",
        "GT",
        "GG",
        "GN",
        "GW",
        "GY",
        "HT",
        "HM",
        "VA",
        "HN",
        "HK",
        "HU",
        "IS",
        "IN",
        "ID",
        "IR",
        "IQ",
        "IE",
        "IM",
        "IL",
        "IT",
        "JM",
        "JP",
        "JE",
        "JO",
        "KZ",
        "KE",
        "KI",
        "KW",
        "KG",
        "LA",
        "LV",
        "LB",
        "LS",
        "LR",
        "LY",
        "LI",
        "LT",
        "LU",
        "MO",
        "MG",
        "MW",
        "MY",
        "MV",
        "ML",
        "MT",
        "MH",
        "MQ",
        "MR",
        "MU",
        "YT",
        "MX",
        "FM",
        "MD",
        "MC",
        "MN",
        "ME",
        "MS",
        "MA",
        "MZ",
        "MM",
        "NA",
        "NR",
        "NP",
        "NL",
        "NC",
        "NZ",
        "NI",
        "NE",
        "NG",
        "NU",
        "NF",
        "KP",
        "MK",
        "MP",
        "NO",
        "OM",
        "PK",
        "PW",
        "PS",
        "PA",
        "PG",
        "PY",
        "PE",
        "PH",
        "PN",
        "PL",
        "PT",
        "PR",
        "QA",
        "RE",
        "RO",
        "RU",
        "RW",
        "BL",
        "SH",
        "KN",
        "LC",
        "MF",
        "PM",
        "VC",
        "WS",
        "SM",
        "ST",
        "SA",
        "SN",
        "RS",
        "SC",
        "SL",
        "SG",
        "SX",
        "SK",
        "SI",
        "SB",
        "SO",
        "ZA",
        "GS",
        "KR",
        "SS",
        "ES",
        "LK",
        "SD",
        "SR",
        "SJ",
        "SE",
        "CH",
        "SY",
        "TW",
        "TJ",
        "TZ",
        "TH",
        "TL",
        "TG",
        "TK",
        "TO",
        "TT",
        "TN",
        "TR",
        "TM",
        "TC",
        "TV",
        "UG",
        "UA",
        "AE",
        "GB",
        "UM",
        "US",
        "UY",
        "UZ",
        "VU",
        "VE",
        "VN",
        "VG",
        "VI",
        "WF",
        "EH",
        "YE",
        "ZM",
        "ZW",
      ],
    },
    phone_number: { required: false, type: "string", maxLength: 128 },
    warehouse: { title: "Warehouse", type: "integer", readOnly: true },
  },
  additionalProperties: false,
};
export const ADMIN_WAREHOUSES_OUT_NOTES_LINES_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    unit_quantity: { required: true, type: "integer", maximum: 2147483647, minimum: 1 },
    unit: { title: "Unit", type: "string", readOnly: true, minLength: 1, nullable: true },
    variant: { title: "Variant", type: "integer", readOnly: true, nullable: true },
    record: { title: "Record", type: "integer", readOnly: true, nullable: true },
    stock_out_note: { title: "Stock out note", type: "integer", readOnly: true },
  },
  additionalProperties: false,
};
export const ADMIN_WAREHOUSES_OUT_NOTES_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    status: {
      required: false,
      type: "string",
      enum: ["Draft", "Confirmed"],
      default: "Draft",
    },
    direction: { required: false, type: "string", enum: ["in", "out"] },
    reason: {
      required: false,
      type: "string",
      enum: [
        "customer_return",
        "partner_return",
        "ecommerce_return",
        "storage_miss_match",
        "product_expiration",
        "other",
      ],
    },
    shipping_incl_tax: { required: false, type: "string", format: "decimal" },
    shipping_excl_tax: { required: false, type: "string", format: "decimal" },
    amount: { required: false, type: "string", format: "decimal" },
    amount_incl_tax: { required: false, type: "string", format: "decimal" },
    notes: { required: false, type: "string" },
    warehouse: { title: "Warehouse", type: "integer", readOnly: true },
  },
  additionalProperties: false,
};
export const ADMIN_WAREHOUSES_PURCHASE_ORDERS_LINES_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    discount_type: { required: false, type: "string", enum: ["Percentage", "Absolute"] },
    discount_amount: { required: false, type: "string", format: "decimal" },
    quantity: { required: false, type: "integer", maximum: 2147483647, minimum: 1 },
    offer_description: { required: false, type: "string" },
    order: { title: "Order", type: "integer", readOnly: true },
    variant: { title: "Variant", type: "integer", readOnly: true, nullable: true },
  },
  additionalProperties: false,
};
export const ADMIN_WAREHOUSES_PURCHASE_ORDERS_RECEIPT_ORDERS_QUANTITIES_WITH_ID_PATCH_SCHEMA =
  {
    type: "object",
    properties: {
      expiration_date: { required: false, type: "string", format: "date-time" },
      notes: { required: false, type: "string" },
      quantity: { required: true, type: "integer", maximum: 2147483647, minimum: 1 },
      order: { title: "Order", type: "integer", readOnly: true },
      line: { title: "Line", type: "integer", readOnly: true },
    },
    additionalProperties: false,
  };
export const ADMIN_WAREHOUSES_PURCHASE_ORDERS_RECEIPT_ORDERS_RETURN_ORDERS_QUANTITIES_WITH_ID_PATCH_SCHEMA =
  {
    type: "object",
    properties: {
      quantity: { required: true, type: "integer", maximum: 2147483647, minimum: 1 },
      order: { title: "Order", type: "integer", readOnly: true },
      receipt_order_quantity: {
        title: "Receipt order quantity",
        type: "integer",
        readOnly: true,
      },
    },
    additionalProperties: false,
  };
export const ADMIN_WAREHOUSES_PURCHASE_ORDERS_RECEIPT_ORDERS_RETURN_ORDERS_WITH_ID_PATCH_SCHEMA =
  {
    type: "object",
    properties: {
      status: { required: false, type: "string", enum: ["Draft"], default: "Draft" },
      surcharge: { required: false, type: "string", format: "decimal" },
      notes: { required: false, type: "string" },
      order: { title: "Order", type: "integer", readOnly: true },
    },
    additionalProperties: false,
  };
export const ADMIN_WAREHOUSES_PURCHASE_ORDERS_RECEIPT_ORDERS_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    status: { required: false, type: "string", enum: ["Draft"], default: "Draft" },
    surcharge: { required: false, type: "string", format: "decimal" },
    notes: { required: false, type: "string" },
    order: { title: "Order", type: "integer", readOnly: true },
  },
  additionalProperties: false,
};
export const ADMIN_WAREHOUSES_PURCHASE_ORDERS_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    status: { required: false, type: "string", enum: ["Draft"], default: "Draft" },
    notes: { required: false, type: "string" },
    warehouse: { title: "Warehouse", type: "integer", readOnly: true },
    partner: { title: "Partner", type: "integer", readOnly: true },
  },
  additionalProperties: false,
};
export const ADMIN_WAREHOUSES_RECORDS_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    low_stock_threshold: {
      required: false,
      type: "integer",
      maximum: 2147483647,
      minimum: 0,
      nullable: true,
    },
    price: { required: false, type: "string", format: "decimal" },
    price_incl_tax: { required: false, type: "string", format: "decimal" },
  },
  additionalProperties: false,
};
export const ADMIN_WAREHOUSES_WITH_ID_PATCH_SCHEMA = {
  type: "object",
  properties: {
    name: { required: true, type: "string", maxLength: 255, minLength: 1 },
    manager: { required: false, type: "integer", nullable: true },
  },
  additionalProperties: false,
};
